// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOEXAsJHTt0ic4frSeADHkbBhlmdCJKi4',
    appId: '1:895644910466:android:7bd907cd75efa81881c59b',
    messagingSenderId: '895644910466',
    projectId: 'authentication-app-44fef',
    storageBucket: 'authentication-app-44fef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUWy1bFKib-ZZAOAiSknPrVDbjvbmWk7A',
    appId: '1:895644910466:ios:ede7a7d6cd69fca381c59b',
    messagingSenderId: '895644910466',
    projectId: 'authentication-app-44fef',
    storageBucket: 'authentication-app-44fef.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZPKfLsyLi-1iXqmjdEHA9qv0MvFFZXIg',
    appId: '1:895644910466:web:8c8bbaedc68c6f6481c59b',
    messagingSenderId: '895644910466',
    projectId: 'authentication-app-44fef',
    authDomain: 'authentication-app-44fef.firebaseapp.com',
    storageBucket: 'authentication-app-44fef.firebasestorage.app',
    measurementId: 'G-KDRDTJV4FG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUWy1bFKib-ZZAOAiSknPrVDbjvbmWk7A',
    appId: '1:895644910466:ios:2c187fc1628df6a881c59b',
    messagingSenderId: '895644910466',
    projectId: 'authentication-app-44fef',
    storageBucket: 'authentication-app-44fef.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZPKfLsyLi-1iXqmjdEHA9qv0MvFFZXIg',
    appId: '1:895644910466:web:268b4b137e8c595881c59b',
    messagingSenderId: '895644910466',
    projectId: 'authentication-app-44fef',
    authDomain: 'authentication-app-44fef.firebaseapp.com',
    storageBucket: 'authentication-app-44fef.firebasestorage.app',
    measurementId: 'G-22EFFMSTHS',
  );

}